apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: efk
  labels:
    k8s-app: elasticsearch-logging
spec:
  ports:
  - port: 9200
    name: api
    protocol: TCP
    targetPort: api
  - port: 9300
    name: transport
    protocol: TCP
    targetPort: transport
  selector:
    k8s-app: elasticsearch-logging
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: efk
  labels:
    k8s-app: elasticsearch-logging
spec:
  serviceName: elasticsearch-logging
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
    spec:
      containers:
      - image: <docker-image>
        name: elasticsearch-logging
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "MINIMUM_MASTER_NODES"
          value: "2"
        - name: "NETWORK_HOST"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9200
          name: api
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: es-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "efk-sc"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
